feat: upgrade module, add test instructions
Mint-System/Odoo-Apps-Account-Invoicing pull request #13
Opened 2024-07-15 12:52 UTC by laszlokr

@janikvonrotz this module also does not carry the sale partner address info from the sales order to the invoice, but only let's to choose the sale partner address in the invoice. Since this field does is not shown on the sales order, it looks like this is taken care of by another module, otherwise the view needs to be extended

2024-07-16 08:32 UTC, janikvonrotz requested changes

2024-07-16 08:32 UTC, janikvonrotz commented on sale_invoice_prepare_partner/tests/TEST_INSTRUCTIONS.rst
> +- Open Sales > Orders > Quotations, create a new quotation for Azure Interior
There should be a step where the `partner_invoice_id` is set on the sale.order.

2024-07-16 08:33 UTC, janikvonrotz commented
The other module is `account_move_invoice_partner`.

2024-08-19 08:35 UTC, janikvonrotz requested changes

2024-08-19 08:35 UTC, janikvonrotz commented on sale_invoice_prepare_partner/tests/TEST_INSTRUCTIONS.rst
I am not sure if this module is actually needed. Does this test work without the module?

2024-08-19 11:45 UTC, laszlokr commented on sale_invoice_prepare_partner/tests/TEST_INSTRUCTIONS.rst
@janikvonrotz it seems the module is still needed, and the sale.order view has to provide the `partner_invoice_id` field to make it work.

2024-08-20 08:15 UTC, janikvonrotz approved these changes

2024-08-20 08:29 UTC, merged